apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      initContainers:
      - name: init
        image: {{ .Values.werf.image.app }}
        command: [ "/bin/bash", "-lec", "for i in {1..10} ; do date ; sleep 1 ; done" ]
      containers:
      - name: app
        image: {{ .Values.werf.image.app }}
        command: [ "npm", "star" ]
